### ISSUE TITLE
tree操作时无法自动获取treeId

### ISSUE THREAD

**Issue by FengBenWu-Org** [wueasy/fslayui#1]
Please answer these questions before submitting your issue. Thanks!
我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的fslayui版本为？）
现阶段最新版本

### Expected behavior （您预期的结果是）
自动获取到treeId

### Actual behavior （实际运行的结果是）
id总是null值，getTree时只会是默认值treeDemo

### Steps to reproduce the behavior （可重现问题的操作步骤）
直接修改tree操作的id，程序会报错

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
无代码，只需要修改tree+table操作的tree的id，就可以复现错误。

**Comment by fallsea** [comment]
请描述使用场景，和使用的代码，如何使用的
