### ISSUE TITLE
demo的表单回调菜单点击报错

### ISSUE THREAD

**Issue by tddsz** [wueasy/fslayui#3]
Please answer these questions before submitting your issue. Thanks!
我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

![exception](https://user-images.githubusercontent.com/39550583/61044774-f562d000-a40b-11e9-848e-525c40e9fdcb.png)

**Comment by fallsea** [comment]
可以了
