### ISSUE TITLE
框架核心问题

### ISSUE THREAD

**Issue by ghost** [wueasy/fslayui#5]
当前使用版本是  2.3.1
问题一:
用iframe模式创业 表单+表格 提交功能页面
框架提示层报错，提示没有这方法
<a class="layui-btn" lay-event="delRow" isConfirm="1" confirmMsg="是否确定删除当前记录？">删除</a>

问题二:
同样是 表单+表格 提交功能页面
表格的列宽度不能自动适应
比如我就 操作列 单独给了列宽 表格是整体宽度是100% 渲染完成后整体自适应出问题

问题三
表单单选框 设置了禁用 当页面css渲染页面时候是 单选框是是可以禁用的   但是框架核心JS方法执行完毕后,重新渲染了一次表单,导致单选框的禁用不起作用

问题四
如何劫持表单的提交，提交前做一些响应的操作  就比如 function="save" 如何重写 或者传入回调参数

问题五
其实我只想用到 表单 里面 的表格功能  框架的侵入性太大
这个功能非常棒  我只想使用原生的Layui的提交监听,然后再获取表单数据+表格数据提价到服务器
没有单独的模块

**Comment by ghost** [comment]
希望能收到您的回复
我的邮箱是 2508310112@qq.com

**Comment by fallsea** [comment]
@Server0308 错误问题，提供一下截图

**Comment by fallsea** [comment]
问题四请看按钮事件或回调事件 https://www.wueasy.com/docs/fslayui/pz/button.html

https://www.wueasy.com/docs/fslayui/form/callback.html

**Comment by fallsea** [comment]
如果需要原生的layui写法，可以不引入`frame.js`
