### ISSUE TITLE
怎么给数据表格添加一行

### ISSUE THREAD

**Issue by hwl962589950** [wueasy/fslayui#6]
Please answer these questions before submitting your issue. Thanks!
我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of fsLayui do you using?（您使用的fslayui版本为？）

2.31
### Expected behavior （您预期的结果是）
现在有一个JSON对象  怎么把这个对象转换成表格中的数据

### Actual behavior （实际运行的结果是）
获取到表格对象添加AddRow 后 表格不见了

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

//表格数据
var datagrid = fsDatagrid.render({id:'fsDatagrid'});

//obj是一个对象
 datagrid.addRow(obj);

然后表格就全部不见了

**Comment by fallsea** [comment]
obj是一行的参数对象
